version: '3'
services:
    mysql:
        image: mysql:5.7.29
        restart: always
        ports:
          - "3307:3306"
        volumes:
          - /usr/local/src/mysql/data/:/var/lib/mysql
        environment:
          MYSQL_ROOT_PASSWORD: password
        networks:
          - savenergy

    coldfusion:
        image: fridus/coldfusion10
        ports:
          - "8088:80"
        environment:
          - CF_DB_HOST=sav_mysql
          - CF_DB_PORT=3307
        volumes: 
          - .:/var/www/html/sav
        links:
          - mysql:mysql
        depends_on:
          - mysql
        networks:
          - savenergy
networks:
    savenergy: